### ISSUE TITLE
Add "back to cart" or "retry payment" link when payment fails

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#138]
When the Braintree payment fails, there is not currently a way for the user to get back to the cart. Additionally, the cart seems to be cleared out. Make sure to preserve the cart contents and give the user a quick way to get back to the payment screen when the Braintree payment fails.

**Comment by brylie** [comment]
The order is being created, but may need to be marked as "payment failed" in the status.

**Comment by marycklein** [comment]
This should be irrelevant, since we are no longer using Braintree. Can we safely close this?
