### ISSUE TITLE
Create process for importing 'offline' subscriptions and migrating Drupal subscriptions

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#156]
Since many subscribers were either created via the Drupal website or from paper forms, we will need a process to migrate those users over and activate subscriptions. We have discussed an invitation process, where links would be sent to user email addresses with some unique token. When the user creates an account on the website, a corresponding subscription would also be activated.

**Comment by marycklein** [comment]
We have crossed this bridge. New challenges face me here in terms of developing a workflow to determine whether to identify website "users" as magazine subscribers or not. But people have been invited to set up a user account, per this issue #156
