### ISSUE TITLE
Use SlimSelect for memorial_meeting field on Memorials filter

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#164]
We have many meetings in the Western Friend community, some of whom will publish memorial minutes. However, all of the meeting names will be displayed in the "memorial meeting" filter field on the Memorials page. Add the SlimSelect widget to make it easier, and more consistent, to find a meeting among the many options.

**Comment by marycklein** [comment]
I am not sure if you applied the solution described in this issue, but the "search by memorial meeting" filter currently on our wagtail website is nicely user-friend.y.
