### ISSUE TITLE
Consider how Editor can be notified of new subscriptions

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#198]
The editor currently gets alerts from PayPal on new payments. Determine how Editor should receive updates about new magazine subscriptions.

**Comment by marycklein** [comment]
Editor actually does receive notifications from PayPal of new subscriptions. Difficulty comes when individual subscribes for themself and then subscribes for another person separately.

**Comment by marycklein** [comment]
OK. I decided to try subscribing for myself at my home address. Then subscribing again for a second person at the Western Friend PO Box. After I successfully subscribed for my home address, I could not get past the attached page to subscribe for a second address. I entirely logged out of the website, then logged back in, and still, when I go to "subscribe magazine" I get stuck on the attached message.

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/7dc07ef3-23ce-47bb-a597-d3218f4132cb)

**Comment by marycklein** [comment]
So, I did have an instance very recently where a person did subscribe twice, about 10 days apart from each other, and I coudn't find via paypal or wagtail who she expected to receive the two different subscriptions. My note to myself about this is attached

[One payor for Two subscriptions.docx](https://github.com/WesternFriend/WF-website/files/13434370/One.payor.for.Two.subscriptions.docx)

**Comment by brylie** [comment]
Currently, the website only allows one subscription per user account. This is mainly due to complexities of managing multiple subscriptions since we moved the subscription management fully to PayPal.

Approximately what percentage of WesternFriend subscribers need to manage multiple personal subscriptions?

As an aside, the subscription use cases we support are intentionally narrow to keep our project simple and maintainable since we have scarce development resources.

**Comment by marycklein** [comment]
You can close this issue as beyond scope of the project.


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
