### ISSUE TITLE
requirements.txt is empty

### ISSUE THREAD

**Issue by NehemiasEC** [WesternFriend/WF-website#221]
the requirements.txt is empty

**Comment by brylie** [comment]
I need to update the development installation directions. 

We now use [Poetry](https://python-poetry.org/) for dependency / virtual environment management. After [installing Poetry](https://python-poetry.org/docs/#installation, try the following:

```sh
poetry shell
```

```sh
poetry install
```

```sh
python manage.py runserver
```

**Comment by NehemiasEC** [comment]
installing poetry in ubuntu20.04 doesnt work from  the poetry website i had to install it from pip. it doesnt work cause poetry use python at the end of the curl installatioon and remember python3 is the default in ubuntu20.04 just saying

**Comment by brylie** [comment]
> installing poetry in ubuntu20.04 doesnt work from the poetry website i had to install it from pip. it doesnt work cause poetry use python at the end of the curl installatioon and remember python3 is the default in ubuntu20.04 just saying

That would be a great issue to raise on the poetry project to help prevent other people from having the same difficulty 🙂

**Comment by brylie** [comment]
I have updated our README to include steps to set up the project with Poetry. Thanks for pointing out this issue with our documentation!

**Comment by brylie** [comment]
@allcontributors please add @NehemiasEC for docs, bug

**Comment by brylie** [comment]
@all-contributors please add @NehemiasEC for docs, bug

**Comment by brylie** [comment]
@all-contributors please add @NehemiasEC for docs, bug
