### ISSUE TITLE
Merge "street address" and "PO box" fields on order form

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#245]
Make the "street address" field required on Bookstore order form. Change help text to say "street address or PO Box". Remove "PO Box" field.

**Comment by marycklein** [comment]
Yes, do make mailing address a required field.

It probably should be labeled  "Reicipient street address and/or PO box" since sometimes, people's correct mailing addresses actually include both, and of course, sometimes one or the other.
