### ISSUE TITLE
Determine if/how to let subscribers change their mailing address

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#248]
E.g. move the subscription mailing address to the `address` table. Create foreign keys to the address on both the subscription instance and user. Allow user to manage address from a "profile" and/or "manage subscription" page.

**Comment by brylie** [comment]
On the "profile" page, call the address "mailing address"

**Comment by marycklein** [comment]
Since address information is only collected by PayPal in our current set-up, this issue is moot.
