### ISSUE TITLE
Only allow users to have one active subscription

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#250]
Our code is currently throwing an error when retrieving the active user subscription. This is because our site allows overlapping subscriptions, so multiple subscription instances are returned from  `Subscription.get()`. In practice, we should only allow one active subscription at a time, no overlaps. Add a constraint to ensure subscriptions cannot overlap, along with changes to the subscription process in #247

**Comment by marycklein** [comment]
It does sometimes happen that one human will subscribe for themself and also for other humans who live at other addresses. I suppose this one human would create multiple, non-overlapping subscriptions. They might one to do this in one transaction.

**Comment by brylie** [comment]
OK, I'll close this. We can look into the issue later. The code currently works correctly when someone has multiple subscriptions.
