### ISSUE TITLE
Include Python version info, migrations step, and superuser credentials in readme.MD

### ISSUE THREAD

**Issue by JoanEliot** [WesternFriend/WF-website#265]
Adding the following info to the readme would help Wagtail novices get the site running locally:

- An explicit statement as to the supported Python version. I'm unfamiliar with poetry, and when I saw that 'requirements.txt' doesn't list non-poetry dependencies I simply followed your instructions to the letter. Installation failed. When I then went rifling through files I found that pocket.lock file lists Python <3.8. That meant having to set up a virtual environment with Python 3.7 (I use conda) and then nest the poetry ve inside that. Installation then went smoothly. 

- Reminder to run migrations before starting the server. I got a 'table not found' error so went back and found that although the migrations have already been made (`runserver makemigrations` -> "`no changes`") they still need to be applied (`runserver migrate`). The web site then opened without error. 

- Reminder to create a superuser and/or the default superuser credentials. Having otherwise followed the readme without deviation, I now found I couldn't access the admin page. That problem was quickly fixed by running  `python manage.py createsuperuser` 

I'm happy to draft an edited readme that speaks to the above points but I'm new to pull requests and don't even know the right lingo for them (do you "make" or "submit" or "pull" a PR?). Will figure out how to do it if you support these changes and want this little contribution.

**Comment by brylie** [comment]
Yeah, the changes sound good.

This dev.to article might be helpful
https://dev.to/codewithfahad/today-i-made-my-first-pull-request-on-github-here-s-how-you-can-do-the-same-3bje

**Comment by brylie** [comment]
Hei @JoanEliot, just checking in. Are you still interested in opening a pull request with the changes you describe above?
