### ISSUE TITLE
Retain filter text/name after selecting a filter (Library page)

### ISSUE THREAD

**Issue by JoanEliot** [WesternFriend/WF-website#267]
Filtering on the [Library page](https://westernfriend.org/library) works great but the page doesn't display the selected filter(s) in the **Filter by** controls. Maybe that's because you're communicating that the filter can still be changed, but I find it disorienting not to see at a glance that the filter I asked for was actually applied, and not to be able to remind myself what filters are currently active. I do see the little breadcrumb-type readout below the banner, but you have to scroll to see it (and it's little). Maybe add a label to each filter category (for example, "Filtered by History") when a filter in that category is active, and change the control text to "Change/remove filter."

**Comment by brylie** [comment]
Closing as resolved

**Comment by brylie** [comment]
@ #@all-contributors please add @JoanEliot for bug
