### ISSUE TITLE
Explore how people can submit files (memorial minutes, magazine articles)

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#309]
When people submit the contact form they sometimes need to submit multiple files, such as memorial minutes. Determine if we should support file uploads via anonymous forms or how to best allow people to submit files.

**Comment by marycklein** [comment]
It seems as though they are not able to attach any documents at all now.

??

This does seem important to resolve. I don't want robots sending me documents . . . But I do want to make it easy for legit Friends to send me legit info.

Maybe we need to advise them of a good way to send text that does not involve attaching a document to a webform? 

Would NextCloud be of any help to us here?

**Comment by brylie** [comment]
One solution would be to request the document via email since email supports file attachments.

**Comment by brylie** [comment]
Discussed with @marycklein during today's call. Agreed to close as wontfix since they added a note on the contact form to send attachments via email.
