### ISSUE TITLE
Determine whether to add a many-to-many "affiliation" relationship between people, meetings, and organizations

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#311]
Mary mentioned that it may at some point be useful to indicate affiliation between people and meetings. By extension, people may also be affiliated with organizations. However, we realize that the "affiliation" feature may lead to other features as well as considerations for the content management process, such as when people change membership or affiliation.

**Comment by marycklein** [comment]
I believe this feature is beyond our capacity to manage / maintain in the longterm. Similar to our aspiration to list the clerks of committees in our "directory of meetings." I can't even manage to get "all" monthly meetings to tell me who is their current presiding clerk when I ask . . . and just the project of "asking all" monthly meetings is quite cumbersome . . . 

I'm closing this as an example of aspiration to overreach.
