### ISSUE TITLE
Add User Profile page

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#32]
We need an initial User Profile page, to serve as the foundation for further work.

## Task
Create a basic User Profile page with the ability to edit:
- first name
- last name
- password

**Comment by marycklein** [comment]
I am promoting this item to "high" priority just to make sure we resolve question of requiring person to provide name when setting up a user account.

**Comment by marycklein** [comment]
I think we can close this one. And I'm doing so.
