### ISSUE TITLE
Register form should require first and last names

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#34]
Currently, the registration form contains first and last name fields that aren’t required. Make sure the fields are required.

# Original issue
Would be helpful to encourage new registrants to share their Monthly Meeting if they have one.

**Comment by marycklein** [comment]
I very much want to "require" new users to give a first name and last name when they register.

**Comment by brylie** [comment]
The topic of requiring first name and last name was resolved in a separate issue #940

**Comment by marycklein** [comment]
I just successfully registered with only an email and a password — no name
Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by marycklein** [comment]
This is fixed! Thanks!
