### ISSUE TITLE
Black?

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#392]
Is this just my eyes? The header one on this page looks less than 100% black to me, relative to the header two, which does look 100% black:
https://sandbox.westernfriend.org/future-issues/

**Comment by brylie** [comment]
I will double-check that no color is being applied when none is specified by adding a conditional check around the field value:

```
if color:
    apply color
```

This is probably a better solution than setting a default value for the color, since it will default to the CSS theme rather than being hard-coded in Python.

**Comment by brylie** [comment]
It looks like the conditional statement already checks whether the color is defined:

https://github.com/WesternFriend/WF-website/blob/e2347b7322e4e8eb73ba3926e0a2b89702ce4d43/streams/templates/streams/blocks/heading.html#L6-L8

I'll check whether this is working correctly.

**Comment by brylie** [comment]
I verified that headings will use the default theme color when none is specified:

![image](https://user-images.githubusercontent.com/17307/172611563-30a6bb3d-d9d5-4b64-a874-15cc2e6ea1d5.png)

I'm removing the default heading color, so it won't go out of sync with the theme default (in case we change the default color later.)
