### ISSUE TITLE
Add sitemap for Magazine content

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#42]
In order to improve search engine indexing, we can publish a sitemap.

## Task
Create a sitemap for the Magazine Articles and Magazine Issues.

**Comment by dhelbegor** [comment]
Hi, can I help with this issue if you allow me :D

**Comment by brylie** [comment]
Sure! This task will mainly involve the [django sitemap framework](https://docs.djangoproject.com/en/2.1/ref/contrib/sitemaps/).

How can I help to get you set up with a development environment? What is your familiarity with Python virtual environments, django, and Wagtail?

**Comment by dhelbegor** [comment]
I'm using docker, I'm very familiar with python / django, but I do not know much about wagtail.

**Comment by brylie** [comment]
Well, the Wagtail sitemap is probably the way to go. Both MagazineIssue and MagazineArticle classes inherit from Wagtail `Page` model, so using Wagtail sitemaps docs will probably make things easier. We just need to configure the Wagtail Site for this project, it seems.

In any case, do whatever seems best to you. I will be happy to get a tutorial on your implementation in the as part of PR review :-)
