### ISSUE TITLE
Design Tweaks - Bookstore page

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#469]
I'd like to reorganize elements per attached. Thanks!
[Design-Tweaks_Bookstore_2022-11-08.pdf](https://github.com/WesternFriend/WF-website/files/9973855/Design-Tweaks_Bookstore_2022-11-08.pdf)

<img width="915" alt="Screenshot 2023-01-25 at 20 56 51" src="https://user-images.githubusercontent.com/17307/214657272-24f5ef40-d96c-4ed4-8be2-114cebba10e9.png">

**Comment by brylie** [comment]
@marycklein, the image provided does not include the book authors. Where should the authors be displayed?
