### ISSUE TITLE
Design tweak - hue of blue of standard "buttons"

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#470]
I would like the blue used in buttons to complement our color palette a bit better, while remaining highly visible.

I started with the "blue" in our WF Color Scheme (hex 5a7584) and adjusted the hue just a tick more toward green and increased the saturation a lot, using:
https://paletton.com/

Attached are the colors I explored, along with my concusion.
[Blue-for-buttons.pdf](https://github.com/WesternFriend/WF-website/files/10018642/Blue-for-buttons.pdf)

**Comment by brylie** [comment]
I've changed the default blue button color to `#06669a`. Since Bootstrap buttons change color on mouse hover, brightening to indicate focus, I've taken the artistic liberty of changing the hover color to `#1283bf` (a lighter, alternative color from the Blue-for-buttons.pdf.)
