### ISSUE TITLE
Design tweaks - Archive scroll button - 2022-11-29

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#477]
![Archive-scroll-button_2022-11-29](https://user-images.githubusercontent.com/44241543/204663125-0b1ff48a-27ae-4ad6-882c-bcd2a4a9d52f.jpg)

**Comment by brylie** [comment]
During our call today, let's discuss the pagination bar since the paginator can have many pages. The "active" page is highlighted in the dark blue, while the other pages are outlined in blue, as in your first example above, with the word "Go."
