### ISSUE TITLE
Styling of links

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#487]
Live links currently styled in text blocks as red font with underline. This is what we agreed.

I suppose it's the "default" display, but link formatting for "URL" in a URL "block" seems to be simple black font. Should probably be red with underline.

They also currently seem to not render as live links when published. Shouldn't they be?

**Comment by brylie** [comment]
Can you include a screenshot or a link to the specific media item on the sandbox so I can explore this issue further? I'll make sure we are using the same links there as in other places on the site.
