### ISSUE TITLE
Text and Images side-by-side

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#488]
I don't see in "library" how to make text and image render side-by-side instead of only as one long running vertical stream . . . ??  Could there be a new sort of "block" available? Could I have three versions of this text-beside-image/media block?

- 2/3 wide next to 1/3 wide
- 1/2 wide next to 1/2 wide
- 1/3 wide next to 2/3 wide

Alternately, it would work well for me to be able to "embed" an image within a text block and have the text wrap around it. In which case, I'd want the choice for image to be left-aligned or right-aligned.

**Comment by brylie** [comment]
Yes, we can add new block(s), so you can do column-oriented layouts. I'll focus on that during the upcoming week. 

Hopefully, I'll be able to make a single block that lets you configure the column count and widths up to a reasonable limit.

Related issue: #343

**Comment by brylie** [comment]
It looks like we can use this plugin:

https://github.com/squareweave/wagtailcolumnblocks

**Comment by brylie** [comment]
One approach to this issue may be to allow images to be floated left and right (instead of creating a columns widget). 

There are currently two ways we add images, for example, to the library item:

1. in the rich text editor, there is an image option (part of Wagtail core)
2. we also have a custom FormattedImageSelect block that allows us to set the image width

It may be possible to extend the RichTextField to add a "Formatted Image" selection that uses the `FormattedImageSelectBlock`. Then, we could extend the `FormattedImageSelectBlock` to allow the content editor to specify an optional float value (left or right.)

https://docs.wagtail.org/en/stable/extending/extending_draftail.html

**Comment by brylie** [comment]
I've asked the Wagtail community how we can specify image alignment and size when selecting an image via the rich text editor.

https://stackoverflow.com/questions/74926606/how-to-extend-the-wagtail-image-format-modal

**Comment by marycklein** [comment]
This progress is encouraging, Brylie.

I realized this might be “an issue” in the context of embedding a “media” (video) on the page, via a URL. Not sure if solution you are seeking would apply to that as well as to “images,” but wanted to note this.

Happy Holidays!!
m



Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
I updated our image chooser block to add an "align" field with options for "left" and "right" alignment. 

![image](https://user-images.githubusercontent.com/17307/210078336-085edb25-08f6-488d-999f-06a2b31e528f.png)

When choosing an alignment value, the image will float to the left or right of the content area. Text will then wrap around the image as shown below:

![image](https://user-images.githubusercontent.com/17307/210078256-98587935-8bf9-479e-a3a7-f91427722818.png)

![image](https://user-images.githubusercontent.com/17307/210078367-6d22483f-4e9c-4e4f-83d0-5720bf44c71d.png)

**Comment by brylie** [comment]
I merged the image chooser changes to be available on the Sandbox for your testing. We can review this feature at our next meeting to determine if we need to do more.

**Comment by marycklein** [comment]
This looks like JUST the thing!

I look forward to giving it a test drive once I ship the magazine off to the printer at 8 AM Wednesday morning. Might not get to do it before we meet on Wed, but the following week for sure!

Happy New Year!!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
