### ISSUE TITLE
Footer tweaks

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#492]
Footer looks REALLY great!! I like the choice of our background color as the font color. Good idea. Some possible vertical alignment adjustments attached.

I realized you dropped the links to FB, Twitter, etc -- which is entirely admirable -- AND . . . We will need to figure out where to give ppl links to our mainstream social media accounts -- FB, Twitter, Instagram, Vimeo, Mastodon (!), GitHub (?) . . .  Even though I'm pathetic in terms of actually posting on these accounts, we need to let ppl know how to find us there.

![Footer-tweaks_2022-12-19_(2)](https://user-images.githubusercontent.com/44241543/208599326-3ebfc026-2810-46aa-b07c-d6326028edbd.jpg)

**Comment by brylie** [comment]
The abovementioned changes are now visible on the sandbox site.
