### ISSUE TITLE
Footer - tweak

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#505]
please add padding to left of "contact us" button in footer so that text doesn't crash into it.
<img width="1232" alt="Add padding to left of Contact Us button" src="https://user-images.githubusercontent.com/44241543/213106713-f4a41733-1179-4eea-8c73-a70d1616998b.png">

**Comment by brylie** [comment]
I added a margin in front of the "Contact Us" button (column), using the Bootstrap minimum margin value of one.

<img width="1263" alt="Screenshot 2023-01-28 at 11 36 52" src="https://user-images.githubusercontent.com/17307/215258991-77723b9e-94a8-45f4-993b-a26e4bb07a4e.png">

This has the effect of visually grouping the contact and social media elements while separating them from the other footer text.

**Comment by brylie** [comment]
I merged the change so it will soon be visible in the sandbox.
