### ISSUE TITLE
Indents in Magazine Issue "Table of Contents"

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#508]
![Magazine T-O-C indents](https://user-images.githubusercontent.com/44241543/213119294-7ce9db7a-31ee-4efc-bfb0-69b3b7356497.jpg)

**Comment by brylie** [comment]
Here is an example of staggered headings and article titles:

<img width="1161" alt="Screenshot 2023-01-25 at 19 07 28" src="https://user-images.githubusercontent.com/17307/214631695-3352c117-ce73-4037-903f-44e64c8ddaa4.png">

**Comment by marycklein** [comment]
Yes! That looks good to me. Call it “done."
Thanks!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
