### ISSUE TITLE
Add suffix field to Author model

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#52]
The Author model contains a `given_name` and `family_name`. However, some author names have suffixes, such as "III" or "Jr."

## Task
Add a suffix field to the Author model.

**Comment by marycklein** [comment]
I think this is unnecessary. Although the suffix is not technically "part" of the person's family name, for all practical purposes, it can simply be included in the "family name" field and will not affect usability of search functions nor accuracy of information shared with public.
