### ISSUE TITLE
Request re Events - Two categories and two corresponding lists

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#523]
![Two Event Categories](https://user-images.githubusercontent.com/44241543/216260384-3fd9b1b3-9316-4c85-8ba6-1f1da2e06e00.jpg)

**Comment by brylie** [comment]
Is it possible for an event to have more than one sponsor? Or, should we only allow one sponsor per event?

**Comment by brylie** [comment]
What would be the URLs for the events pages? E.g.
- westernfriend.org/events (Western Events)
- westernfriend.org/events/other (Other Events)

**Comment by brylie** [comment]
After looking more closely at this code, I've come up with the following design for the URLs

- westernfriend.org/events/ -- Western events
- westernfriend.org/events/?category=other -- other events

This allows us to use the category to filter the events without having to define a new page type in the code. At the same time, we can create separate links in the navigation menu or elsewhere to direct visitors to the Western and Other events separately.

**Comment by marycklein** [comment]
This sounds just right! Well done! And a big thanks!

Looking forward to talking with you soon!

m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by marycklein** [comment]
Theoretically, an event could have more than one sponsor. Practically, I think this happens almost never.

If it makes everything work more smoothly, architecture-wise, we could limit events to having one sponsor, and then co-sponsors could be givien credit in the text that describes the event.

m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
Just a note: as per our discussion, I updated the Event model to allow multiple sponsors.

**Comment by marycklein** [comment]
Excellent. Thanks!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
