### ISSUE TITLE
Media Library pagination should elide excess pages

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#548]
The Media Library pagination will show any arbitrary number of pages, leading to the paginator extending off the page. Determine how to elide excess pages showing at most ten with an ellipsis, next, previous, first, and last buttons.

Resources

https://realpython.com/django-pagination/

**Comment by rezarex** [comment]
Hi @brylie , can I work on this?

**Comment by brylie** [comment]
Sure, @rezarex. Thanks!
