### ISSUE TITLE
NavBar and Drop-Down Menues

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#552]
Here is how I think these should be set up.
<img width="1067" alt="NavBar Drop-Downs" src="https://user-images.githubusercontent.com/44241543/223677487-12da9616-77aa-4153-8f16-8450caa9c7f8.png">

**Comment by brylie** [comment]
This seems to be a duplicate of issue #537 and it's continuation issue #537

**Comment by brylie** [comment]
Podcasts will be a static page.

Extra Extra will be included in #540
