### ISSUE TITLE
Design tweak - Number One Header

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#565]
I'd like to try making the Number One headers BOLD.
Also add a little vertical space above them.
![Number One header adjustments](https://user-images.githubusercontent.com/44241543/228130712-6c12feb6-d385-4bcd-b923-69ebca324bca.jpg)

**Comment by brylie** [comment]
A more general approach to this task would be to increase the bottom margin from the navigation menu/header so that every site page uses the same spacing.
