### ISSUE TITLE
Design tweak - Color of links (again/still)

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#566]
This is one place where it would be especially nice to override the blue in that link.
![Link to match red](https://user-images.githubusercontent.com/44241543/228130972-4e79049f-8f9c-4527-a7ab-802c81962174.jpg)

**Comment by brylie** [comment]
Of course, using the same color for both visited and unvisited links is possible. 

The middle link may have been visited, while the other two are unvisited links. Ideally, we would preserve the expected browser behavior by distinguishing between visited and unvisited links. For example, we can vary the saturation between visited and unvisited links, as described in this article:

http://universalusability.com/access_by_design/links/differentiate.html

We should remember that we are already using alternatives to commonly used link colors, which means visitors to the Western Friend website will have more of a learning curve when navigating around.
