### ISSUE TITLE
Enhancements to Extra Extra section

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#571]
Split from #542 

@marycklein wrote

> I believe we have decided to organize these to rely on essentially the same sets of "genre" and "topic" terms that we are using for faceted search in "media library" (though for "extra extra," we would say "type" rather then "genre" for news items).
>
> Going forward in Wagtail, I will enter "event" news items as "events," and I will enter all other items as "news items." This is assuming we can sort "events" into "western events" and "other events"
>
> The actual "news items" will either be a subset of items in the "media library" (one yes/no filter in library that asks: do these go in the "periodicals" section of the library, or instead "on the shelves"?) or, alternately, they could continue to be their own distinct category of content on the website.
>
> Also excellent would be to allow (but not require) items to be associated with monthly meetings and/or yearly meetings and/or individuals. New items should NOT require "authors" per se, since I am generally simply forwarding news items that other people have forwarded to me. I generally do not know the original authors of these news items.

**Comment by brylie** [comment]
@marycklein and I agreed to leave this for post-launch due to the complexities of adding data columns since they don't exist in the current site data export.

**Comment by marycklein** [comment]
I am closing this issue as it is redundant with another that talks about coordinating filters used in library and news
