### ISSUE TITLE
Describe process to upload/create data via CSV or similar format

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#59]
Mary would like to be able to export data from other systems and import them into the WF website. We need to determine what systems this includes, how their data are structured, and how to map/import the data.

**Comment by brylie** [comment]
The main need here is to be able to bulk update items.

**Comment by marycklein** [comment]
This is no longer a relevant issue. I believe this might have been a concern when we were still looking forward to data migration from Drupal to Wagtail.
