### ISSUE TITLE
Notifications to User

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#633]
Post-launch issue: Develop a simple method to notify WF Editor that they have messages they need to respond to; especially in terms of:

- "Contact Us" messages
- "People" accounts needing authorizations (active, subscriber, board member, etc.)

**Comment by brylie** [comment]
One idea was to add these as Dashboard indicators in the Wagtail Admin.

**Comment by marycklein** [comment]
I think this issue asking for direct notifications is closed.

"contact us" messages ARE successfully being forwarded to MCK via email.

MCK workflow to assign "subscriber" authorization to "users" would benefit from some changes, but not in terms of getting individual notifications when "users" create accounts
