### ISSUE TITLE
(PYL-C0209) Consider using f-strings

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#636]
## Description
f-strings are the fastest way to format strings as compared to the following methods: * using format specifiers `%`

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-C0209/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-C0209/occurrences/)

**Comment by Harshal662** [comment]
plz assign it to me

**Comment by brylie** [comment]
Thanks :-)
