### ISSUE TITLE
(JS-0125) Found the usage of undeclared variables

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#641]
## Description
Variables that aren&#x27;t defined, but accessed may throw reference errors at runtime. &gt; **NOTE**: In browser applications, DeepSource recommends the use of ESModules over regular `text/javascript` scripts. &gt; Using variables that are injected by scripts included in an HTML file is currently not supported.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/JS-0125/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/JS-0125/occurrences/)

**Comment by lokeshkadem** [comment]
@brylie Sir, u wish to define the function[cleanForSlug()] or remove it
