### ISSUE TITLE
(PYL-W0221) Mismatched parameters in overridden method

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#644]
## Description
The parameters in the overridden method don&#x27;t match the method defined in the parent class. There are three possible scenarios for this: - The number of parameters are different in both methods - One or more names of the parameters are different in both methods - The order of parameters …

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-W0221/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-W0221/occurrences/)

**Comment by viktoriussuwandi** [comment]
Hi [brylie](https://github.com/brylie),
If this issue still open & available, I would like to help on this issue.

Do you have any idea on my solution below :

Current code :
[line 173-174](https://github.com/WesternFriend/WF-website/blob/d34aed15eceee25321ee91b2dc7af6cce1a07857/magazine/models.py#L173)
[line 326-333](https://github.com/WesternFriend/WF-website/blob/d34aed15eceee25321ee91b2dc7af6cce1a07857/magazine/models.py#L326)

My Solution :
I will add parameter `priority` on [line 173](https://github.com/WesternFriend/WF-website/blob/d34aed15eceee25321ee91b2dc7af6cce1a07857/magazine/models.py#L173), 
and little format the indentation.
So it will looks like :

```
    def get_sitemap_urls(self, priority=None):
        return [
            {
                "location": self.full_url,
                "lastmod": self.latest_revision_created_at,
            },
        ]
```
