### ISSUE TITLE
(PTC-W0027) `f-string` used without any expression

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#647]
## Description
It is wasteful to use `f-string` mechanism if there are no expressions to be extrapolated. It is recommended to use regular strings instead.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PTC-W0027/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PTC-W0027/occurrences/)

**Comment by GT-Codeur** [comment]
Hello @brylie , I think we should close this issue. I can't find the peace of code where f-string are misused.
Kind regards.
