### ISSUE TITLE
(PTC-W0048) `if` statements can be merged

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#648]
## Description
Nested `if` statements can be collapsed into a single `if` statement by separating their condition using `and` operator. Merging collapsible `if` statements increases the code&#x27;s readability.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PTC-W0048/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PTC-W0048/occurrences/)

**Comment by P-Pole** [comment]
Hello @brylie,

It is pretty straight forward change. If you could assign me to the issue, I would be more than happy to help.

**Comment by brylie** [comment]
Thanks @P-Pole :-)

**Comment by brylie** [comment]
An alternative solution would be to convert the function-based view to a class-based view.

https://docs.djangoproject.com/en/4.2/ref/class-based-views/base/#django.views.generic.base.View

In general, I'm steering towards class-based views.
