### ISSUE TITLE
(PYL-R1705) Unnecessary `else` / `elif` used after `return`

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#654]
## Description
The use of `else` or `elif` becomes redundant and can be dropped if the last statement under the leading `if` / `elif` block is a `return` statement. In the case of an `elif` after `return`, it can be written as a separate `if` block. For `else` blocks after `return`, the …

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-R1705/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-R1705/occurrences/)

**Comment by Harshal662** [comment]
Hey I can work on this issue if you assigned it to me, seems straightforward. Furthermore, can I work on other issues that suit me without asking you to assign them to me or do I have to ask?

**Comment by brylie** [comment]
Thanks @Harshal662 :-)

**Comment by Harshal662** [comment]
I have viewed all the code the necessary changes were already made you can close this issue.
