### ISSUE TITLE
(PYL-W0107) Unnecessary `pass` statement

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#656]
## Description
The `pass` statement used here is not necessary. You can safely remove this.

## Occurrences
There are 4 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-W0107/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PYL-W0107/occurrences/)

**Comment by viktoriussuwandi** [comment]
Hi [brylie](https://github.com/brylie), May I try to help on this issue ?
