### ISSUE TITLE
(FLK-D200) One-line docstring should fit on one line with quotes

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#659]
## Description
If a docstring fits in a single line (72 characters according to PEP8), it is recommended to have the quotes on the same line.

## Occurrences
There are 13 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/FLK-D200/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/FLK-D200/occurrences/)

**Comment by viktoriussuwandi** [comment]
Hi [brylie](https://github.com/brylie), May I try to help on this issue ?

**Comment by brylie** [comment]
Thanks @viktoriussuwandi :-)
