### ISSUE TITLE
(FLK-D202) No blank lines allowed after function docstring

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#660]
## Description
There shouldn&#x27;t be any blank lines after the function docstring. Remove the blank lines to fix this issue.

## Occurrences
There are 8 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/FLK-D202/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/FLK-D202/occurrences/)

**Comment by lokeshkadem** [comment]
i resolved this issues please look at this @brylie
