### ISSUE TITLE
(PY-D0002) Missing class docstring

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#661]
## Description
Class docstring is missing. If you want to ignore this, you can configure this in the `.deepsource.toml` file. Please refer to [docs](https://deepsource.io/docs/analyzer/python/#meta) for available options.

## Occurrences
There are 255 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PY-D0002/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PY-D0002/occurrences/)

**Comment by klorine28** [comment]
hello could I get some more context on this issue?

**Comment by brylie** [comment]
Sure. Deepsource scanned our source code and identified many function, class, and method definitions that are missing documentation, such as Python doc strings. In the issue description, there is a link to the full Deepsource report showing where we can improve the project. The goal of this issue is to improve project maintainability by adding relevant documentation.
