### ISSUE TITLE
(PY-D0003) Missing module/function docstring

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#662]
## Description
The module/function docstring is missing. If you want to ignore this, you can configure this in the `.deepsource.toml` file. Please refer to [docs](https://deepsource.io/docs/analyzer/python/#meta) for available options.

## Occurrences
There are 123 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/WesternFriend/WF-website/issue/PY-D0003/occurrences/](https://app.deepsource.com/gh/WesternFriend/WF-website/issue/PY-D0003/occurrences/)

**Comment by Karansankhe** [comment]
please assign me these issue
