### ISSUE TITLE
improve test coverage for `accounts` app

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#680]
The `accounts` app currently has a low test coverage score:

- https://app.codecov.io/gh/WesternFriend/WF-website/tree/main/accounts
- https://app.codecov.io/gh/WesternFriend/WF-website/blob/main/accounts%2Fmanagers.py
- https://app.codecov.io/gh/WesternFriend/WF-website/blob/main/accounts%2Fmodels.py

## Task

- improve the test coverage to above 85-90% (so coverage turns green instead of yellow or red)

**Comment by alhcomer** [comment]
Hiya, I'd like to do be assigned to this issue if possible.

**Comment by alhcomer** [comment]
I've written tests for the accounts app. However when trying to create a branch to make a pull request I am running into errors associated with mypy requiring type annotations for accounts/models and subscription/models. 

Apologies if this is me being stupid, this is my first time trying to contribute to open source

**Comment by brylie** [comment]
Thanks @alhcomer!
