### ISSUE TITLE
improve test coverage for `donations` app

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#683]
The `donations` app currently has a low test coverage score:

- https://app.codecov.io/gh/WesternFriend/WF-website/tree/main/donations
- https://app.codecov.io/gh/WesternFriend/WF-website/blob/main/donations%2Fmodels.py

## Task

- improve the test coverage to above 85-90% (so coverage turns green instead of yellow or red)

**Comment by alhcomer** [comment]
Hiya, I'd like to be assigned this if it's available :)

**Comment by brylie** [comment]
Hey, @alhcomer. How are you progressing with this task?
