### ISSUE TITLE
Ensure all content models have Drupal migration metadata

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#719]
We want to ensure that data migrates correctly from Drupal to WagtailCMS. To that end, we have three fields that help us re-run the migrations and ensure we create content redirects:

```py
drupal_node_id = models.IntegerField(null=True, blank=True)
drupal_body_migrated = models.TextField(null=True, blank=True)
drupal_path = models.CharField(max_length=255, null=True, blank=True)
```

Task
- ensure all content models contain those fields
- if possible, use an abstract base model to reduce code duplication

**Comment by ErnstBas** [comment]
Hi @brylie. Can I help with this one?

There are 16 `models.py` files, but I am not sure if you consider each of them as a content model. In any case, I could add to all these files an abstract model class, like this:

```
class DrupalFields(models.Model):
    drupal_node_id = models.IntegerField(null=True, blank=True)
    drupal_body_migrated = models.TextField(null=True, blank=True)
    drupal_path = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        abstract = True
```

And than make sure that all present classes not only inherit Page, but also DrupalFields, like this:  
`class CommunityPage(DrupalFields, Page)`

Correct?

Just a detail: 
In `community/models.py`, the three lines are already present, except for the last one. There is `drupal_url_path` instead of `drupal_path`:

```
drupal_node_id = models.IntegerField(null=True, blank=True)
drupal_body_migrated = models.TextField(null=True, blank=True)
drupal_url_path = models.CharField(max_length=255, null=True, blank=True)
```

**Comment by brylie** [comment]
Thanks @ErnstBas. 

The relevant content models currently inherit from Wagtail Page model, so we would need to keep that inheritance, possibly using multi-inheritance or a mixin strategy. At some point in the future, I will likely remove these fields from all models, so the approach should be easy to migrate away from.

Here are the relevant models, to the best of my recollection:

- community: OnlineWorship
- documents: BoardDocument, MeetingDocument
- events: Event
- library: LibraryItem
- magazine: ArchiveIssue, MagazineIssue, MagazineArticle
- memorials: Memorial
- news: NewsItem
- wf_pages: WfPage, MollyWingateBlogPage

**Comment by brylie** [comment]
Basically, I want to preserve the raw data from Drupal in the content migration process. So, any model that has a `drupal_node_id` and `body` will be a good candidate for keeping the `drupal_body_raw`. That way, I can "re-run" the `parse_body_blocks` method on migrated entities, if I notice any errors with the initial migration after launch.

A good place to check for the `url_path` usage is in the `content_migration.management` handlers. Those are the migration scripts invoked by the related management commands.
