### ISSUE TITLE
Display article author(s) name(s) on magazine issue page

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#736]
The magazine issue page currently lists magazine article titles grouped by department. However, the articles should also include the author's name(s), as is done on the current website.

<img width="416" alt="Screenshot 2023-06-27 at 10 15 47" src="https://github.com/WesternFriend/WF-website/assets/17307/dcf794e4-d83c-483d-a535-f7404d029a5b">

Update the Magazine Issue template to display each article's related author's name(s).

**Comment by AryanGupta0007** [comment]
Do i need to run the docker commands to contribute to this project?

**Comment by AryanGupta0007** [comment]
and also do i need to install postgress db as i m getting a error relating to that while migrating

**Comment by AryanGupta0007** [comment]
please tell me what database is being used in this project ? The engine in the settings.py suggests sqlite3. but i had encountered a problem earlier which was relating to postgress so i had installed that . After that it said that i need to configure the password and username in the settiings.py file so i need help with that as i new to postgress . 

        "ENGINE": os.environ.get("DATABASE_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("DATABASE_NAME", ":memory:"),
        "USER": os.environ.get("DATABASE_USER", ""),
        "PASSWORD": os.environ.get("DATABASE_PASSWORD", ""),
        "HOST": os.environ.get("DATABASE_HOST", ""),
        "PORT": os.environ.get("DATABASE_PORT", ""),
        "TEST": {"NAME": os.environ.get("DATABASE_NAME", "")}, ## specifically need help to fill this db name here. Kindly guide

**Comment by brylie** [comment]
Please find instructions for starting the project in our contributing guide:

https://github.com/WesternFriend/WF-website/blob/main/docs/CONTRIBUTING.md

**Comment by ErnstBas** [comment]
Hello @brylie, can I help with this one?

**Comment by brylie** [comment]
Sure, thanks @ErnstBas. I'll assign you. There is some reference code on the Magazine Article page that would be useful for this task.
