### ISSUE TITLE
Fix Article metadata display on small and medium devices

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#738]
The Magazine Article metadata display currently overlaps on small and medium screens:

<img width="301" alt="Screenshot 2023-06-27 at 11 00 42" src="https://github.com/WesternFriend/WF-website/assets/17307/54470f8f-85d0-4f73-8b80-981a00c87c9e">

## Task

- [ ] adjust the markup so the columns have more room to display the values on small and medium screens (using Bootstrap breakpoint semantics)

**Comment by GT-Codeur** [comment]
Even this issue should be closed. It works well now.

**Comment by brylie** [comment]
Thanks @GT-Codeur :-)
