### ISSUE TITLE
MCK Review One - Overview

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#784]
I gave a fairly hard look at "all" pages of the "staging" version of the new WF website on July 16-17, 2023. I'm calling this "MCK Review One." I will post all items in the attached list as separate issues.
[Review One Tweaks - Overview 2023-07-17.xlsx](https://github.com/WesternFriend/WF-website/files/12077164/Review.One.Tweaks.-.Overview.2023-07-17.xlsx)

**Comment by brylie** [comment]
Let's consider closing this issue, since all of the items in the spreadsheet seem to be accounted for in the GitHub issues list.

**Comment by marycklein** [comment]
I have just completed a cross-check of the changes we made in Github regarding open issues (eg, tagging as pre/post launch) — against my own inventory, which is organized according to the structure of the menubar on our site, and which inventory is contained in this closed issue #784.

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
