### ISSUE TITLE
Display of books for sale

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#793]
Can we display these items in two columns?

**Comment by brylie** [comment]
I split the issue "Prioritize Faith and Practice books in Bookstore display" so that the current issue can be more focused.

**Comment by marycklein** [comment]
Maybe two columns isn't "the answer" here. The "problem" is an undue amount of white space. Maybe "the answer" is to include complete book description for each book in the listing on this page; not to truncate the text, that is. Then just live with whatever "excess" white space remains.

**Comment by marycklein** [comment]
The way we have this set up currently is just fine.
