### ISSUE TITLE
Change header to "Library / Media," add intro.

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#794]
@marycklein will add intro text during staging.

![RevOne_3 1-3 2_search-library-media](https://github.com/WesternFriend/WF-website/assets/44241543/2f528ef5-21e5-4ec0-a3cf-231ca0dd5c03)

**Comment by brylie** [comment]
We can manually add the instructions after the page is created for simplicity. 

I'll update the page title in the import script.

**Comment by marycklein** [comment]
I am now of the opinion that the "introductory text" on our Drupal site is unnecessary. I now believe the page is sufficiently self-explanatory that a visitor should be able to find their way without that text.
