### ISSUE TITLE
Add intro text to "news" listing

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#795]
![RevOne_3 3_extra-extra-news](https://github.com/WesternFriend/WF-website/assets/44241543/f63a7421-9a33-409e-83ca-ae4ccce1eb08)

**Comment by marycklein** [comment]
need to have intro text that applies to both "western events" and "other news"

**Comment by brylie** [comment]
The implementation would resemble the following:

Fields
- western_events_intro: RichText
- other_events_intro: RichText

Then, in the template, use the same logic that toggles between the "Western Events" and "Other Events" heading.

**Comment by marycklein** [comment]
good.

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by marycklein** [comment]
This was done!
