### ISSUE TITLE
MCK Review One - 3.6 - Problem with "search" in Memorials

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#798]
The "person" search is pulling up results from article titles in Library and News; it should instead display names of people whose memorial minutes are in our collection

**Comment by brylie** [comment]
I believe this is related to browser auto-complete. In effect, the form field is called "title, " which is pretty generic. Your web browser may suggest previous searches from any form field called "title." 

I can see if we can make the form field name more specific, but I suggest we plan this for post-launch.

**Comment by marycklein** [comment]
It looks like you fixed this "search person" problem. Or at least, it's behaving correctly for me today. Thanks! 

However, the problem has now morphed into a new one. Which is -- In the case of a large meeting like Palo Alto, with lots of memorial minutes, when you ask the "meeting" filter to search for results from Palo Alto, the results say they have delivered three pages of lists of memorial minutes, but when you click on "next" for "page 2" of the list, the search function tosses you out of the Palo Alto results and back into the general collection of results from random meetings. (And  -- I checked this -- it's not a matter of these random results being people who have "palo alto" mentioned in the body text of their memorial minutes)

**Comment by brylie** [comment]
Ok. I think I know why that search bug is happening with the Palo Alto search example.

**Comment by marycklein** [comment]
yay!

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by marycklein** [comment]
Just confirming decision to forego "intro text" on this page.
