### ISSUE TITLE
"Board of Directors" needed

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#800]
MCK to draft this page in sandbox.

**Comment by marycklein** [comment]
The following Drupal page is now categorized in the new Drupal page collection, "Page for Staging New Site." It is an acceptable and workable draft page: https://westernfriend.org/board-directors

**Comment by marycklein** [comment]
The following page is also now in the collection "Page for Staging;" there is a link near the middle of the "board of directors" page links to this second page, which then links onward into four collections of pages that together contain about 40 more pages. https://westernfriend.org/cultivate-quaker-experience

**Comment by marycklein** [comment]
Would it be helpful for me to categorize each of those 40 (+/-) pages as members of the collection "Page for Staging"?

**Comment by brylie** [comment]
All of the Drupal pages will be imported automatically, so there isn't any need for another page category on Drupal.

**Comment by marycklein** [comment]
this page was created on staging platform 9/19/2023
