### ISSUE TITLE
Change header to "Directory of Meetings," make YM subheaders bolder

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#801]
![RevOne_4 3_directory-of-meetings](https://github.com/WesternFriend/WF-website/assets/44241543/5a31ca1d-9e44-4f95-aa8c-426df6d4cf0a)

**Comment by brylie** [comment]
I have updated the card heading text to be bold. However, we will need to change the "Community" text to "Directory of Meetings" in the staging environment, since that is not defined in code.
