### ISSUE TITLE
Directory of Meetings - contact info only

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#802]
Let's just stick to the listing of contact info for meetings here; pretty much the same content as we have on Drupal site; maybe post-launch we can set up some sub-pages to display other content associated with each YM
![RevOne_4 4_directory-for-individ-YM](https://github.com/WesternFriend/WF-website/assets/44241543/f271a7a2-66cc-431b-a73c-9d966f725ec9)

**Comment by brylie** [comment]
We would need to develop specific templates for Meetings since they currently use a shared template for all Contacts (Meetings, Organizations, and People). This is possible, but we should consider whether to do it pre- or post-launch.

**Comment by brylie** [comment]
When I import the full CiviCRM content, the contact information will display above all related content. I'll check whether the CiviCRM addresses importer is in the main import script.

We agreed that the related content, such as epistles and articles, is good to show on the Meeting page but should display below the regular contact information.

**Comment by marycklein** [comment]
This is how I remember what we agreed to also.
Thanks!!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
I have verified locally that the meeting pages will correctly display their contact details and sub-meetings.
<img width="1211" alt="Screenshot 2023-08-05 at 23 10 41" src="https://github.com/WesternFriend/WF-website/assets/17307/330ead01-4835-4f2f-a5fb-1bb2211eee0c">
