### ISSUE TITLE
"Contact Us" page / form needed

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#803]
We still need to create this page.

**Comment by brylie** [comment]
It already exists, but the form rendering appears to be an issue. 

https://preview.westernfriend.org/contact/

I'll label this as a bug.

**Comment by brylie** [comment]
I looked into this and remembered Wagtail allows us to define the form in the Wagtail Admin. So, the form had yet to be defined on the preview website. Likewise, we must create the form while staging the website before launch.

So, this isn't a bug, after all, just another administrative detail. 😄

**Comment by marycklein** [comment]
Sounds good. Let me know if I can work on this.
m

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
