### ISSUE TITLE
Online Worship results to display by day etc.

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#805]
Can we figure out a way to display these results by day of week, etc, rather than alphabetical by meeting name?

**Comment by brylie** [comment]
Yes, the events can be grouped by day. I'm still determining what other groupings we want to consider, but let's keep things simple for now. 

Also, let's consider addressing this issue post-launch since it isn't a blocker currently.

**Comment by marycklein** [comment]
1)   post-launch for final version where this mimics creation and listing of  "events;" 2) minimum viable = MCK builds a simple page that menu bar links to, which is a page of links to current individual pages for  individual online worship options

**Comment by marycklein** [comment]
3) Following is the page we can use as a placeholder "landing page" for now. This links to about 80 individual pages for individual repeating worship events. All these pages are in the “online worship” collection. (well they should be): https://westernfriend.org/quaker-worship-and-fellowship-online

**Comment by marycklein** [comment]
I set up a "landing page" for "online worship," for which Brylie has corrected the URL so that this will be "the page" that visitors find post-launch
