### ISSUE TITLE
Western/Other Events to have compact listing similar to online worship

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#806]
![RevOne_5 3_consistent-formatting-events](https://github.com/WesternFriend/WF-website/assets/44241543/c34aed96-d463-4a5c-af31-f29a49b0a751)

**Comment by brylie** [comment]
@marycklein to propose a holistic design for the Western Events, Other Events, and Online Worship. It is worth mentioning that the Online Worship page is separate from the "Western Events/Other Events" page.

**Comment by marycklein** [comment]
Yes. And Brylie observed that the two “event” pages list one-time events; whereas the “worship” page lists repeating events. So although it would be good for viewer to see a similar graphic format on all three pages, they contents would be populated somewhat differently.

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
