### ISSUE TITLE
Make it more clear that "teaser" is not a complet text

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#812]
Truncate long passages in search results.
![RevOne_9 2_search-results](https://github.com/WesternFriend/WF-website/assets/44241543/18e729a6-9377-429c-8d91-7a75facfafdc)

**Comment by brylie** [comment]
It looks like the image didn't upload in the issue description. It says, "Uploading RevOne_9.1_search-results.jpg..." but there isn't a file there. When dragging and dropping (or selecting and uploading) images, make sure to give it some time to finish uploading before saving the issue description.

**Comment by brylie** [comment]
I assigned myself and added this to post-launch since it doesn't block the launch from happening.

**Comment by marycklein** [comment]
I am closing this issue because adding the "subscribe now" button AFTER the "teaser" should send this message to the reader.
