### ISSUE TITLE
MCK Review One - 6.7 - Need "help wanted" page

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#815]
MCK to draft in sandbox.

**Comment by brylie** [comment]
Drupal would be the better place to draft this page so that it will be imported to the new site. Alternatively, we can wait to create it after launch.

**Comment by marycklein** [comment]
1) This Drupal page is in the new Drupal page collection, "Page for Staging New Site." It is an acceptable and workable draft page.  https://westernfriend.org/help-wanted; 2) Following four pages link from above, and are all also included in collection “page for staging” https://westernfriend.org/books-review-western-friend, https://westernfriend.org/brief-biographies-historic-quakers, https://westernfriend.org/proofreading-guide-western-friend, https://westernfriend.org/future-issues

**Comment by marycklein** [comment]
This "new" page imported from Drupal. We have an empty and redundant "help wanted" page in our collection now. I need to make sure all links to "help wanted" go to the page with text before we delete the empty page
