### ISSUE TITLE
Use unified pagination widget across site

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#825]
We currently have pagination on a few pages, such as in the Events, Library, Magazine, and Memorials app. Since all of our pagination relies on Django paginator, we should be able to use some shared template for the pagination UI. That way, the UI will remain consistent across the site.

## Task

- [ ] create a shared pagination template (using the Library pagination as the most complete working example)
- [ ] use the shared template anywhere we use pagination in the app (i.e., the template can take a `paginator` context variable)

**Comment by rajbhoyar729** [comment]
can you assign to me
