### ISSUE TITLE
Directory of Meetings - displays of individual meetings

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#874]
We need to confirm once all data exports / imports that . . . 

Each YM displays its appropriate lists of QMs and MMs first . . . then it can list stray articles, etc at the bottom

Each MM displays its appropriate data

**Comment by brylie** [comment]
The community directory is now ready for review: https://staging.westernfriend.org/community/

**Comment by marycklein** [comment]
I believe this directory is pretty solid now. I do want to go through and add "manual time stamps" to all the directory pages, noting their "last known to be current" dates. I'm going to try shifting this issue to be a "post launch" item now.

**Comment by brylie** [comment]
Closing as complete
