### ISSUE TITLE
Subscribe to Magazine - subscribe by mail

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#875]
Add intro text that says “Click here to subscribe by mail.”
Above text would link to this page: https://westernfriend.org/subscribe-mail

**Comment by marycklein** [comment]
I added this intro text in the form of two sentences that each link to a page: 
[To subscribe by ground mail, look here for details.](https://staging.westernfriend.org/subscribe-by-mail/)

[Quaker Meetings may receive discounted pricing on group subscriptions to Western Friend; read about it here.](https://staging.westernfriend.org/about-group-subscriptions/)

We'll want to make sure that this intro text survives the re-formatting with new approach to payment processing via PayPal.

**Comment by brylie** [comment]
Closing as complete
