### ISSUE TITLE
Extra Extra - news listed by yearly meeting, type, topic

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#881]
I added these "sorted news listing pages to our staging site. See: https://staging.westernfriend.org/extra-extra-western-friend/

Sadly, all the individual news items listed in the sub-pages are all linked as "external links" to the pages on Drupal.

Is there any way to "bulk" redirect those links to the "internal" pages which I believe pretty much all did import into Wagtail?

**Comment by brylie** [comment]
The bulk editing shouldn't be necessary since these are absolute links, starting with westernfriend.org, that will point to the Wagtail website once we point westernfriend.org to Wagtail.
