### ISSUE TITLE
Directory of Meeting - drop "more information" button

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#891]
Please delete "more information" button at the bottom of individual meeting's online worship pages.
It is very confusing to the naive visitor.

Also, there is some variability among meetings about whether they provide a zoom link or not. Most do, but not all. Not sure that affects what is currently ending up in this "more info" field, but I think we should hide it for now and revisit it more thoughtfully post-launch.

**Comment by brylie** [comment]
Please provide a screenshot and, if possible, a link to a specific page where the "more information" button is displayed.

**Comment by brylie** [comment]
I'll remove the button style but leave the link, since the link directs people to the official meeting information pages.

**Comment by brylie** [comment]
Here is one example I was able to locate: https://staging.westernfriend.org/community/online-meetings-for-worship/apple-seed-cotati-ca/

**Comment by brylie** [comment]
It is worth mentioning that currently many online worship pages use the rich text field to contain all online worship details including links. 

We learned from Drupal that we need to introduce more structure to our data so we can display it to users in a consistent manner, such rich text content isn't always structured consistently.

With these online worship pages, we know there is almost always a website link to the actual online worship room or details. So, we have a field now for that website link, which allows us to display the link to the online worship in a consistent manner, as well as adding semantic information or even opening the link in a different tab.

**Comment by marycklein** [comment]
Yes, I was not really thinking carefully when I posted this issue.

I think the problem is just one of labeling.

I think the visitor needs to see a label that says something like “Enter online worship here.” or “Click here for online worship.”

To have this link labeled “More information” or “Website” leads the visitor to expect to arrive at something expansive. The point here is that we are providing something very specific.

It was not the “button” that I objected to, now that I’m actually thinking about this, it was just the words.

So. Would you please re-title that field for the videoconferencing link with some expression you like that is similar to my two suggestions above?

If it is a super-easy thing to re-format that as a “button,” I actually think that would be better. But a simple bare link, like what you’ve got going now, would be fine for now.

THANKS!!
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
