### ISSUE TITLE
Footer image overlaps table of contents on Deep Archive issues

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#892]
When viewing any issue from the Deep Archive, the site footer overlaps the table of contents.

## Task

- [ ] fix the deep archive issues template so the table of contents will display above the site footer.

**Comment by matejtuke** [comment]
Hey, can ou assign this issue to me? Thank you

**Comment by jitesh-sidhani** [comment]
In deep archive section , the image is overlapping. Can you assign me this issue

**Comment by brylie** [comment]
> In deep archive section , the image is overlapping. Can you assign me this issue

Please create a new GitHub issue with that information, so I can assign you.

**Comment by brylie** [comment]
Closing as no longer relevant
