### ISSUE TITLE
Directory of Meetings - Display page date for each meeting

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#895]
We lost the field from CiviCRM where I could note when each individual monthly meeting and worship group page was last updated and would display that info to visitors

Can you create a field in wagtail form where I can communicate that info? Month and year would be ideal

Can you export a CSV file from CiviCRM that correlates names of monthly meetings and worship groups with that date info from that manually completed field?

**Comment by brylie** [comment]
Sure. Ideally, this field would be automatically updated whenever the page data is changed. Since this is so common, Django provides us a way to set the `updated_at` field whenever the page is saved. I can look into the automatic solution and set the default value to a recent date, since we have been auditing the content recently.

**Comment by marycklein** [comment]
Let’s make sure we have the option to override the automatic date.

There might be a case where I corrected a spelling error on old information that I don’t actually know whether it’s current.

When I ask people to check the info, maybe half of them respond. In our current Meeting records, I’d say about half of them are current as of Sept 2023, and the others were last updated in 2020 or 2021.

m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by marycklein** [comment]
Just to be redundant . . . Half of our meeting pages should display dates that let visitors know the info has not been confirmed since 2020 or 2021.

This is why I asked if you could give me a field in wagtail that I can fill by hand “now." Ideally, you can also do the other thing I requested of exporting the data from that field that currently exists in CiviCRM. Then i could enter the data manually at my leisure later. Otherwise, I’ll need to do it “now” while I can still have wagtail and CiviCRM both open at the same time.

Hope that made sense.
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by marycklein** [comment]
I think it should not be too hard for me to compile a list of all “last reviewed by” dates.
Ideally, I will enter those into this new field before we redirect the public to Wagtail.
But I’ll get myself prepared with the information in the next couple days so as to not need to rely on CiviCRM.
Thanks!!


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652

**Comment by brylie** [comment]
OK, sounds good. I've added the field and it should now be visible in the staging website.
