### ISSUE TITLE
Add Braintree subscription plans

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#904]
We currently don't have subscription plans defined in our Braintree production account for:

- monthly-recurring-donation | Monthly recurring donation  - every 1 month - $0
- recurring-donation - recurring donation (obsolete?) - every 12 months - $0
- yearly-recurring-donation - Yearly recurring donation - every 12 months - $0

**Comment by brylie** [comment]
When I try to add the subscriptions, I get the following errors:

- Plan could not be created. Please see below for errors.
- Merchant must have an active merchant account.

![image](https://github.com/WesternFriend/WF-website/assets/17307/0e7038e5-30ed-45a6-a1d0-7738db0eb799)

**Comment by marycklein** [comment]
This is now moot.
