### ISSUE TITLE
Switch to PayPal for payment processor

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#906]
We currently use Braintree for the payment processor but have decided to use PayPal instead. In order to switch to PayPal, we need to update the `payment` module to render the PayPal form as well as updating the relevant views that currently use Braintree.

- [x] https://github.com/WesternFriend/WF-website/pull/907
- [ ] Donations will use a regular PayPal button so we need a place to display the button that triggers the modal
- [x] Subscriptions
    - [x] for manual subscriptions add an `expires_on` date field (optional)
    - [x] paypal subscription ID takes precedent over expires on
    - [x] otherwise, some subscriptions may be perpetual (no paypal ID no expires on)

## Resources

https://developer.paypal.com/docs/checkout/standard/integrate/

**Comment by brylie** [comment]
## Findings
- PayPal Bookstore payments were relatively easy to implement (around 8 hours)
- PayPal donations will need to use the PayPal button flow (pictured) and don't allow users to specify arbitrary text input (so won't be useful for Donate/pay)
- The paypal.me service is designed to allow people and organizations to accept arbitrary payments, so would be a strong candidate for the Pay part of Donate / Pay (use the tools we already have)
- PayPal subscription flow will impose some constraints on what is possible, such as reducing the number of available subscription types due

## Mock-ups
Below are two mockups for the Donate and Subscribe pages respectively.

### Donate
![donate](https://github.com/WesternFriend/WF-website/assets/17307/4daf8480-e96d-49fa-9838-acdd3957b9de)


### Subscribe
![subscribe](https://github.com/WesternFriend/WF-website/assets/17307/3b6d9e16-6d87-45cf-9916-5deaddfa2f37)


## References

- https://developer.paypal.com/docs/multiparty/subscriptions/customize/multiple-buttons-website/
- https://www.paypal.com/paypalme/

**Comment by brylie** [comment]
##Benefits of Migrating to PayPal:

- Streamlined Integration: By utilizing the default PayPal buttons for subscriptions and donations, we can significantly reduce the complexity of our codebase. This means less custom coding, which in turn can lead to fewer potential bugs and issues down the road.
- Trust and Recognition: PayPal is one of the most recognized and trusted payment platforms worldwide. For users, seeing a familiar PayPal button can instill a greater sense of trust and security in making a transaction.
- Easier Maintenance: A simpler codebase is easier to maintain. This will not only potentially reduce future development costs but can also make it easier to address any issues that might arise, ensuring a smoother user experience.
- Potential for Greater Uptake: Due to its widespread recognition, some users might prefer using PayPal over other payment options. This could potentially lead to an increase in subscriptions or donations, as users might feel more comfortable transacting through a platform they recognize and trust.

## Concerns and Trade-offs:

- Limited Design Control: As observed, PayPal will have a larger say in the design and user flow for payments, donations, and subscriptions. This means we will have less control over the exact look and feel, which may or may not align with our brand's aesthetic.
- Centralized Data Management on PayPal: Having all subscription data exclusively managed on PayPal might pose challenges, especially if we decide to migrate to another platform in the future or if we wish to integrate additional services.
- Potential for Feature Limitations: Given that more full integrations, like syncing subscription prices, are out of scope for this project, there might be limitations on what we can achieve in terms of features or customizations.

**Comment by marycklein** [comment]
Here is a list of 12 Paypal "subscription plans" for Western Friend magazine
[PayPal Subscription Plans - WF magazines.docx](https://github.com/WesternFriend/WF-website/files/12890572/PayPal.Subscription.Plans.-.WF.magazines.docx)

**Comment by marycklein** [comment]
QUESTION: Can I change amounts in "shipping and handling" for books when I "create" books in "staging" version of website? Postal costs have really gone up in last ten years and I should increase these amounts by a bit. However, if that would create some sort of coding nightmare for you, I can wait to make this pricing change some time next year.

**Comment by brylie** [comment]
We can change the shipping price structure in the code without difficulty.
