### ISSUE TITLE
Subscribe - Pay for magazine subscriptions

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#911]
Mary needs a link to the new PayPal friendly "subscribe" page. The version that displays "publicly" on the staging site is the previous version designed for BrainTree.

**Comment by brylie** [comment]
I'm completing this work in issue #906

**Comment by brylie** [comment]
The subscribe buttons can now be configured on the Staging website. For familiarization, please edit the following page and add the desired remaining subscription options.

https://staging.westernfriend.org/subscribe/

[PayPal.Subscription.Plans.-.WF.magazines.docx](https://github.com/WesternFriend/WF-website/files/13073920/PayPal.Subscription.Plans.-.WF.magazines.docx)

**Comment by marycklein** [comment]
Hurry!
I’ll do that before we meet Wed.
If all goes well . . . 
best
m


Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
