### ISSUE TITLE
Library - new items to be top of list

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#918]
I just published seven new pages in the "library" on the staging site. 

In the NovDec magazine, I tell people they can go to the library to find these items.

When I posted them just now, they did not show up at the top of the queue as they should have, but at the end. The seven are listed oldest-to-newest among themselves on page 50. They should be listed newest to oldest on page one. That is, new items should appear on page one in this order: 

1. Seeds of a Healthy Life
2. Sink Down to the Seed - And Get Nourished
3. Healing Collective Trauma
4. Job Scott's Remarks on the Knowledge of the Lord
5. Holding the Light to Change Torture
6. The Words Would Not Stop Coming
7. Podcast 27 – Abortion and Community

**Comment by marycklein** [comment]
By the Way . . . Creating these pages was SUPER pleasant in terms of editor's user experience. MUCH better than struggling with Drupal!

**Comment by marycklein** [comment]
Just checked to see if there's been any progress here. Doesn't look like you've had a chance yet.

However -- I now notice on page-turning-widget at bottom . . . "next" and "last" behave properly, but "first" and "previous" both act like "previous." This is with Firefox browser.

**Comment by brylie** [comment]
Go ahead and open a separate issue for the page turning widget bug so this issue stays focused on the sort order.

**Comment by marycklein** [comment]
Yes. Good. Will do.
m

Mary Klein
Editor / Executive Director

Western Friend
2625 Middlefield Road, #565
Palo Alto, CA  94306-2516
650-318-1652
