### ISSUE TITLE
Library - Page-turning widget error

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#919]
On page-turning-widget at bottom  of "library / media" page . . . "next" and "last" behave properly, but "first" and "previous" both act like "previous." This is with Firefox browser.

**Comment by brylie** [comment]
I’ve tested on the staging website and the buttons are functioning as intended. E.g., when viewing the first page of results and clicking Next, I am taken to page two. When clicking Last, I am taken to page 50.

Can you upload a video showing the bug happening in your browser? What browser(s) have you used when encountering this issue?

**Comment by marycklein** [comment]
I did not describe the problem well.

The problem is when I click "first." if I am on 4, it goes to 3.  If I am on 45 and click "first," it goes to 44. It does the same thing as "previous" does.

And I did say it was with Firefox. But I did not say the version of Firefox, which is 119.0 and claims it is "up to date."

I just tried in Safari 17.1 -- same.

**Comment by brylie** [comment]
Verified. Will fix the “First” button.
