### ISSUE TITLE
Use a standard option set for site-wide rich text editor consistency

### ISSUE THREAD

**Issue by brylie** [WesternFriend/WF-website#945]
We currently define StreamField settings on a per-model basis, leading to inconsistencies across models. It may be desirable to define a global constant streamfield settings list, so all site streamfields have the same capabilities.

## Task

- [ ] define a global STREAMFIELD_SETTINGS constant, such as in the core/settings.py
- [ ] use the new constant in every streamfield for consistency

**Comment by brylie** [comment]
Assigned. Consider using the current values from the magazine.models.MagazineArticle.body field for default site-wide streamfield value.

**Comment by GT-Codeur** [comment]
Hello @brylie , I'm having this error: `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`
When I'm creating the list `STREAMFIELD_SETTINGS = [
    ("heading", HeadingBlock()),
    (
        "rich_text",
        wagtail_blocks.RichTextBlock(
            features=[
                "bold",
                "italic",
                "ol",
                "ul",
                "hr",
                "link",
                "document-link",
                "superscript",
                "superscript",
                "strikethrough",
            ],
        ),
    ),
    ("pullquote", PullQuoteBlock()),
    ("document", DocumentEmbedBlock()),
    ("image", FormattedImageChooserStructBlock(classname="full title")),
    ("spacer", SpacerBlock()),
]` inside the `settings.py` file.

So I propose that we create a file constants.py

**Comment by brylie** [comment]
The `core/constants.py` sounds like a great idea :-)

**Comment by GT-Codeur** [comment]
Hello @brylie I think this should be closed.
