### ISSUE TITLE
Allow regular subscriber access to intro text on to "Subscribe" page

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#956]
Issue discussed here has been addressed. Thanks.

**Please see related issue at bottom of this thread.** Concerning the "non-super" registered user.

Original issue, now "fixed" --

Today, logged in as "editor@westernfriend.org", I wanted to look at the subscription page, and instead, when I clicked on "subscribe," I got the message attached, which offers no live links to take me anywhere else.

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/4c8c564d-14f3-4ac0-8a69-06856f4b81b7)

**Comment by marycklein** [comment]
I am discovering that I must have been logged in still as "editor@westernfriend.org" when I "subscribed" to the magazine using my paypal account connected to my personal Yahoo email address. don't know if that contributed to this issue.

**Comment by brylie** [comment]
Ah that makes sense. Is your goal to edit the subscription page?

**Comment by brylie** [comment]
As a partial workaround. I can try to make it so the subscription page is still editable by the admin while preventing people from trying to subscribe twice when they have an active subscription.

**Comment by brylie** [comment]
I've just made a change that lets "superuser" accounts access the subscription page to make changes to the texts, etc.. I've also included a warning to advise superusers not to create a subscription via that page under their superuser account, since it can lead to unexpected difficulties and errors. I hope this resolves the issue so you can now edit the subscription page :-)

**Comment by marycklein** [comment]
This is a good solution. Thanks!

I would like it if a regular subscriber was able to access the links that give info about current subscription prices, ordering by ground mail, and group subscriptions for monthly meetings -- the three links in the intro text when a person is not logged in. Would it be possible for a logged-in subscriber to see the "subscribe - Magazine" page like the attached?

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/b0c512fb-f703-4368-aad0-24bf10bdab85)

**Comment by brylie** [comment]
That sounds possible. How about adding an intro text field to the "Manage Subscription" page that lets you put arbitrary text and links on that page?

**Comment by brylie** [comment]
I just double-checked and the "Manage Subscription" page already has an intro text field, so you can put any freeform text, links, etc.

![image](https://github.com/WesternFriend/WF-website/assets/17307/b30baf0f-41dc-4464-8c5a-6343e9ce4de7)
