### ISSUE TITLE
Board Photos page - validation error

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#959]
Cannot update Board Photos Page

https://westernfriend.org/board-documents/board-photos/

When I attempt to edit this page, it tells me “changes cannot be saved due to validation errors.”

**Comment by brylie** [comment]
Are there any red fields or text on the edit screen that might point to which field(s) failed validation?

**Comment by brylie** [comment]
There was an empty RichText block on the Board Photos page so it was keeping the page from saving.
