### ISSUE TITLE
Bookstore - can't go "back to bookstore" from cart

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#964]
When put an item from the bookstore into the cart, then click "back to bookstore," get the following error message

![Image](https://github.com/WesternFriend/WF-website/assets/44241543/56329db8-b556-4456-a6a6-401004cd80f5)

**Comment by marycklein** [comment]
yikes. I just tried removing an item from my cart and the whole page went totally blank. I clicked on the little trash can next to one of the books

**Comment by brylie** [comment]
Let's open separate issues for the white screen and the back-to-bookstore link. That way, the problems can be resolved independently since they likely have different underlying causes.
