### ISSUE TITLE
Vimeo embeds have disappeared from the media library

### ISSUE THREAD

**Issue by marycklein** [WesternFriend/WF-website#967]
I see they are missing from the podcast pages, which I spent some hours formatting in a consistent manner, so I know they were there before. I have not gone looking yet to see if they are missing elsewhere.

**Comment by marycklein** [comment]
indeed . . . I sorted the library by "media" and it appears all the pages that are supposed to display videos are no longer displaying videos.

With luck, the links will be available in a back-up of the webiste.

**Comment by brylie** [comment]
I've just checked the code and for some reason the embedded media block was missing from the LibraryItem streamfield. I've added the Embedded Media support back to the Library Item edit form. We will need to manually add the missing video files (YouTube and Vimeo links) found in the attached CSV file.
[library_items.csv](https://github.com/WesternFriend/WF-website/files/13503342/library_items.csv)

**Comment by brylie** [comment]
Closing this as resolved after @marycklein noted that the videos are mostly still available (after restoring the embed option in the RichText field.)
